# Goal definition
ShortVariedNested short_varied_nested # Comment - Nesting Level 3: 1 of 2
---
# Result definition
bool bool_value # Comment - Nesting Level 3: 2 of 2
---
# Feedback definition
bool[3] bool_values
